services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_jwtdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwtdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jwt_auth_backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/jwtdb?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3000
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql_data:
